<?php

namespace AppBundle\Repository;

/**
 * ItemPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemPostRepository extends \Doctrine\ORM\EntityRepository
{
}
