<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * ItemPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemPostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllItemsByUser(User $user){
        return $this->createQueryBuilder('item_post')
            ->andWhere('item_post.user = :user')
            ->orderBy('item_post.postDate', 'DESC')
            ->setParameter('user', $user)
            ->getQuery()
            ->execute();
    }

    public function findAllAndSortByDate(){
        return $this->createQueryBuilder('item_post')
            ->orderBy('item_post.postDate', 'DESC')
            ->getQuery()
            ->execute();
    }
}
